version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ord-app-store-ord_ord_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  ord:
    image: cryptovengeance/ord:latest
    # This needs to run as root
    # user: "1000:1000"
    restart: on-failure
    # First-inscription-height may not be needed in the future
    command: "ord --first-inscription-height 767430 --index-runes --data-dir /var/lib/ord --bitcoin-data-dir /var/lib/bitcoind --bitcoin-rpc-url ${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT} --chain ${APP_BITCOIN_NETWORK} server --http"
    volumes:
      - ${APP_DATA_DIR}/data/ord:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/var/lib/bitcoind:ro
